#!/usr/bin/env python3
"""Transform symbol graph JSON files into structured CSVs for LLM consumption.

Reads all .symbols.json files from an input directory and produces:
  - api-surface.md  — index describing available data and CSV schemas
  - types.csv       — all public types (classes, structs, enums, protocols)
  - methods.csv     — all public methods/properties with signatures
  - relationships.csv — conformances, inheritance, memberOf relationships

Usage: generate-docs-transform.py <input-dir> <output-dir>
"""

import csv
import json
import os
import sys
from pathlib import Path


def extract_doc_comment(symbol):
    """Extract doc comment text from a symbol, if present."""
    doc = symbol.get("docComment", {})
    lines = doc.get("lines", [])
    if not lines:
        return ""
    return " ".join(line.get("text", "").strip() for line in lines).strip()


def extract_declaration(symbol):
    """Extract the declaration string from fragments."""
    fragments = symbol.get("declarationFragments", [])
    if not fragments:
        return ""
    return "".join(f.get("spelling", "") for f in fragments).strip()


def module_name_from_path(filepath):
    """Derive module name from a .symbols.json filename."""
    name = Path(filepath).name
    # Remove .symbols.json or .symbols.N.json
    name = name.split(".symbols")[0]
    return name


TYPE_KINDS = {"class", "struct", "enum", "protocol", "typealias"}
METHOD_KINDS = {
    "method",
    "type.method",
    "init",
    "deinit",
    "func.op",
    "type.property",
    "property",
    "subscript",
}


def process_symbol_graph(filepath, types_rows, methods_rows, relationships_rows):
    """Process a single symbol graph JSON file."""
    with open(filepath) as f:
        data = json.load(f)

    module = module_name_from_path(filepath)
    symbols_by_id = {}

    for sym in data.get("symbols", []):
        precise_id = sym.get("identifier", {}).get("precise", "")
        symbols_by_id[precise_id] = sym

        kind = sym.get("kind", {}).get("identifier", "")
        # Strip "swift." prefix if present
        kind_short = kind.replace("swift.", "")
        name = sym.get("names", {}).get("title", "")
        access = sym.get("accessLevel", "")
        doc = extract_doc_comment(sym)
        declaration = extract_declaration(sym)
        path_components = sym.get("pathComponents", [])

        if kind_short in TYPE_KINDS:
            types_rows.append([module, kind_short, name, access, doc])

        elif kind_short in METHOD_KINDS:
            parent = path_components[0] if len(path_components) > 1 else ""
            methods_rows.append([module, parent, kind_short, name, declaration, doc])

    # Relationships
    for rel in data.get("relationships", []):
        kind = rel.get("kind", "")
        source_id = rel.get("source", "")
        target_id = rel.get("target", "")

        source_sym = symbols_by_id.get(source_id, {})
        target_sym = symbols_by_id.get(target_id, {})

        source_name = source_sym.get("names", {}).get("title", source_id)
        target_name = target_sym.get("names", {}).get("title", target_id)

        relationships_rows.append([module, source_name, target_name, kind])


def write_api_surface_md(output_dir, modules):
    """Write the api-surface.md index file."""
    md = """# API Surface

Pre-analyzed API documentation for this project's Swift modules.
Generated by `/generate-docs`. Re-run that command to refresh after code changes.

## Available Modules

{module_list}

## Data Tables

### Types

**File:** [`types.csv`](types.csv)

All public types across all modules.

| Column | Description |
|--------|-------------|
| Module | The Swift module this type belongs to |
| Kind | Type kind: class, struct, enum, protocol, typealias |
| Name | The type name |
| Access | Access level (public, open, internal, etc.) |
| Doc comment | Documentation comment, if present |

### Methods & Properties

**File:** [`methods.csv`](methods.csv)

All public methods, properties, and subscripts.

| Column | Description |
|--------|-------------|
| Module | The Swift module this member belongs to |
| Parent type | The type this member belongs to |
| Kind | Member kind: method, type.method, init, property, type.property, subscript |
| Name | The member name |
| Declaration | Full Swift declaration |
| Doc comment | Documentation comment, if present |

### Relationships

**File:** [`relationships.csv`](relationships.csv)

Type relationships: conformances, inheritance, membership.

| Column | Description |
|--------|-------------|
| Module | The Swift module |
| Source | The source type |
| Target | The target type |
| Kind | Relationship: conformsTo, inheritsFrom, memberOf, etc. |
"""
    module_list = "\n".join(f"- {m}" for m in sorted(modules))
    content = md.format(module_list=module_list)

    with open(os.path.join(output_dir, "api-surface.md"), "w") as f:
        f.write(content)


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input-dir> <output-dir>", file=sys.stderr)
        sys.exit(1)

    input_dir = sys.argv[1]
    output_dir = sys.argv[2]
    os.makedirs(output_dir, exist_ok=True)

    types_rows = []
    methods_rows = []
    relationships_rows = []
    modules = set()

    # Process all symbol graph files
    for filename in sorted(os.listdir(input_dir)):
        if not filename.endswith(".json"):
            continue
        filepath = os.path.join(input_dir, filename)
        module = module_name_from_path(filepath)
        modules.add(module)
        try:
            process_symbol_graph(filepath, types_rows, methods_rows, relationships_rows)
        except (json.JSONDecodeError, KeyError) as e:
            print(f"Warning: skipping {filename}: {e}", file=sys.stderr)

    # Write CSVs
    with open(os.path.join(output_dir, "types.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Module", "Kind", "Name", "Access", "Doc comment"])
        w.writerows(types_rows)

    with open(os.path.join(output_dir, "methods.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Module", "Parent type", "Kind", "Name", "Declaration", "Doc comment"])
        w.writerows(methods_rows)

    with open(os.path.join(output_dir, "relationships.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Module", "Source", "Target", "Kind"])
        w.writerows(relationships_rows)

    # Write index
    write_api_surface_md(output_dir, modules)

    # Output summary as JSON for the shell script
    summary = {
        "modules": sorted(modules),
        "types": len(types_rows),
        "methods": len(methods_rows),
        "relationships": len(relationships_rows),
    }
    json.dump(summary, sys.stdout)


if __name__ == "__main__":
    main()
